site_name: Midi Controller
site_url: https://mppowell.github.io/midi-controller

plugins:
  - glightbox

theme:
  name: material
  font:
    text: Anek Latin
    code: input-mono

extra_css:
  - https://use.typekit.net/hka8mpg.css
  - stylesheets/extra.css